### PR TITLE
Prevents publishing without an index.html and displays error.

### LINKED ISSUE #1952: Publishing projects without index.html fails to locate it.
When publishing project without index.html file, the resulting link leads to a broken project. 

no_index

While the resulting page has a suggestion on potential cause of the problem, however the existence of index.html should be checked at the publish time, and feedback should provided. Maybe block the publish button and provide feedback here:

no_index_2

### PR DESCRIPTION
**Pull request by flukeout**
If you try to publish without having an ``index.html`` page, it does the following:

_no-indexerrr

Link in the error message goes to the [answer in the wiki](https://github.com/mozilla/thimble.mozilla.org/wiki/Using-Thimble-FAQ#why-do-i-need-an-indexhtml-file-when-publishing-my-project).

Currently, the link is embedded into the localization string, should I extract it @TheoChevalier ?

Builds on work started in #1994 by @dsych.

Fixes #1952

### CODE REVIEW

**Comment by TheoChevalier** [comment]
> Currently, the link is embedded into the localization string, should I extract it @TheoChevalier ?

@flukeout Definitely safer if you do, but clearly not a blocker if you don’t.

**Comment by flukeout** [comment]
Thanks, @TheoChevalier - I moved the URL into a variable [here](https://github.com/mozilla/thimble.mozilla.org/pull/2238/files#diff-c9a9094a335b05ca97f4236da1e41d8aR38), mind taking a quick look?

**Comment by TheoChevalier** [comment]
> Thanks, @TheoChevalier - I moved the URL into a variable here, mind taking a quick look?

LGTM, thank you 👍

**Comment by flukeout** [comment]
Thanks @TheoChevalier ! Merging and thanks again to @dsych for doing the bulk of the work! 👍

**Pull request merged**
