### PR TITLE
Fixes #1815 - Feature: Delete multiple projects

### LINKED ISSUE #1815: Request: Ability to delete multiple projects at once
taking inspiration from imgur and google's android client, it would be nice if there was a "batch delete" option, where clicking the "trash" icon marks an element as "to be deleted" with a new button "DELETE THIS" popping up at the top of the page, so you can click more trashcans and select more than 1 project to delete in the same batch, with the "are you sure?" dialog not popping up until you press the button up top.

### PR DESCRIPTION
**Pull request by kramsamujh**
Added functionality to delete multiple projects. Was unsure of the styling of everything so I just went with what seemed to make sense.

### CODE REVIEW

**Comment by kramsamujh** [comment]
@Pomax @flukeout Could one of you guys check this out? Also, is the branch conflict something I need to fix on my end?

**Comment by flukeout** [comment]
Hey @kramsamujh - thanks so much for submitting the PR - sorry for the slow reply. Would you mind rebasing your branch to the latest master so that it merges cleanly? I'll try it out then.

Thank you!

**Comment by kramsamujh** [comment]
@flukeout got my branch rebased to the latest master. It should be good to test out now.

**Comment by flukeout** [comment]
Hey @kramsamujh - this is a super sweet PR! I just tried it out and really liked it. Would you be able to update this PR (or submit a new one) that doesn't include all of the commits related to the localizations. You could make a brand new branch from master and then just copy the contents of the two files you modified into that.

Once you do that, I'll submit a PR against your branch with some styling updates. Sound good? 

Thanks again, this is a cool change!

**Comment by Pomax** [comment]
I *love* this ❤️

**Pull request closed without merging**
