### PR TITLE
Create help.md

### PR DESCRIPTION
**Pull request by jgmac1106**
Updated the Thimble help file that currently lives in wiki

### CODE REVIEW

**Comment by humphd** [comment]
Great work!  Can I request that we add 2 things:

* &lt;a name="..."&gt; sections to each header/question so that we can also add a:
* table of contents at the top.

**Comment by Pomax** [comment]
small counterpount: `<a name...>` is no longer valid under HTML5 rules, with same-document linking achieved by pointing to `id` attributes instead. Just add an id to any element you need to be able to jump to and then link to them with `<a href="#thatid">go there</a>`

**Comment by jgmac1106** [comment]
Okay I didn't add the anchor tags as it seemed get hub turned any h2 markdown element into a the id attribute.

I also didn't know rules of the road for how it will look on SUMO.

Noob question: I have no idea how to get back to make changes to a file once a pull request has been submitted. How?

**Comment by jgmac1106** [comment]
So I went in and added the id attribute. I guess it comes down to where the content is goign to live. If we are going to put this on the GitHub wiki there is no need to add the attribute as h2 in markdown seems to autogenerate an anchor link that could be used for a ToC.

When I added the id attribute to the questions then I messed up the markdown. Should it the attribute name inside of the hashmarks?

The other option is just add a help.html file as well as the markdown file and let folks choose to do whatever they want.

**Comment by humphd** [comment]
You do anchors in markdown like this: https://gist.github.com/asabaylus/3071099

**Comment by jgmac1106** [comment]
Thx will update once kids go to bed.

**Comment by gideonthomas** [comment]
@jgmac1106 since this is github markdown (we can think about transitioning to where it will live eventually later), you actually don't need `<a id="...">` for them since they are header elements (\#) and automatically have an `id` available that you can use to link to.
For e.g.:
## This is a Heading

[this is a link to the heading](#this-is-a-heading)


And the actual markdown I used was:
\#\# This is a Heading

\[this is a link to the heading\](#this-is-a-heading)

**Comment by jgmac1106** [comment]
Okay going back and pulling out the id elements bringing us full circle to where we began. I hope everyone has a wonderful week.

**Comment by Pomax** [comment]
Another thing I completely forgot to mention: github already auto-links your markdown, so if you have a heading like
```
### how to make cake
```
that can be hotlinked inside the same document using `[how to make cake](#how-to-make-cake)

**Comment by flukeout** [comment]
Thanks so much for this content @jgmac1106 - as I mentioned in mattermost, I've moved it into the Wiki and added a Table of Contents: https://github.com/mozilla/thimble.mozilla.org/wiki/Using-Thimble-FAQ

**Comment by Pomax** [comment]
@flukeout before closing this issue, can we make sure that link is surfaced in the README.me too?

**Comment by humphd** [comment]
I think we need to deal with the duplication of wiki pages:

* https://github.com/mozilla/thimble.mozilla.org/wiki/Using-Thimble
* https://github.com/mozilla/thimble.mozilla.org/wiki/Using-Thimble-FAQ

These are very similar.  Maybe we should dump the first one and use this better one that @jgmac1106 has created?  Also, the README points to the second one, and should probably point to the first.

@jgmac1106 would you be willing to drive this effort in new bugs/PRs since you're the most up to date on what we have now?

**Comment by jgmac1106** [comment]
I can drive (::fire:: ::red-car::) but do not have the rights (nor do I trust myself not to screw up if I did) to push commits, but yeah you can assign me as lead.

I will bring us back to the one wiki page and then also update the readme.md file. What branch should I be working from?

**Comment by humphd** [comment]
Do PRs and we'll review help you fix anything, then land.

You should do all your work on a new branch off of master:

```
git checkout -b fix-docs master
// edit your files, maybe README.md
git add README.md
git commit -m "Updated README.md to do x, y, z"
git push origin fix-docs
```

Then you can do a PR from there on GitHub.  I've written detailed instructions on this here: http://blog.humphd.org/howto-first-github-pr/

Please ignore all of this if you already know it, I wasn't sure your comfort level with git.

**Comment by flukeout** [comment]
I think one way to tackle this would be just remove the questions that relate specifically to features from the FAQ doc so we would have:

* FAQ that includes common problems / troubleshooting
* Feature Guide

**Comment by flukeout** [comment]
I'll take this on.

**Comment by flukeout** [comment]
Okay, it seems like we have all of this content in the wiki already - https://github.com/mozilla/thimble.mozilla.org/wiki/Using-Thimble-FAQ

I'm going to close this and instead maybe we link to the wiki from the README.md file. I just don't want there to be two places where we host this and the wiki is a bit more useful since it's easier to link to it for users.

**Pull request closed without merging**
