### PR TITLE
issue-1949 fix for button styling

### PR DESCRIPTION
**Pull request by Abykin**
Fixes 1949 listed here : https://github.com/mozilla/thimble.mozilla.org/issues/1949. Adding opacity to the button styling.

### CODE REVIEW

**Comment by humphd** [comment]
Adding @flukeout for review.

**Comment by flukeout** [comment]
Hi @Abykin - thanks for submitting, to properly address the Issue, we need to add a class to the button after it is clicked and then apply some different styling based on that class. The change you provided only changes the hover styling, which is not enough.

So, when the button is clicked
* Let's add a ``.disabled`` class to it.
* Add styles for the ``.disabled`` class that
  * Turn the button grey
  * Remove the ``:hover`` & ``:active`` styling so that it doesn't change when it's clicked or hovered.

Does that make sense? Let me know if you have any questions.

**Comment by Abykin** [comment]
@flukeout I've not done css like that before, would it be something like this :
$("#new-project-button-text").addClass( "disabled" );

And in css file would add a .disabled class with the grey property and removed :hover and :active styling?

**Comment by flukeout** [comment]
@Abykin Yeah, taht's exactly right. Wherever the click handler is for that **New Project** button is where you'll want to do the ``addClass`` method. Chances are, there is already some kind of reference to the button like ``_self.button`` or something so you can use that instead.

We don't really ever have to worry about removing the class, since it will always start on the page without it.

Let me know how it goes - or just update your PR with your work and we can go from there. Thanks!

**Comment by Abykin** [comment]
@flukeout Hey I got the button to take the gray color once clicked : 
image
Is this how we want it?

**Comment by flukeout** [comment]
Testing it out now @Abykin

**Comment by flukeout** [comment]
Oh wait, you haven't updated the PR yet. Once you push your changes up, let me know and I'll test haha.

**Comment by Abykin** [comment]
@flukeout Hi sorry about that forgot to push! New commit added

**Comment by flukeout** [comment]
Cool, will try again!

**Comment by flukeout** [comment]
Hey @Abykin this is great. The only change I'd like to request is to make the button background a little lighter so it's easier to read the label. If you change the ``.disabled`` styling to the following...

```
.disabled {
  color: gray;
  background: rgba(0,0,0,.2) !important;
  border-bottom: solid 2px rgba(0,0,0,.2);
}
```

We should get this....

image

Cheers!

**Comment by Abykin** [comment]
@flukeout Added the background colors

**Comment by gideonthomas** [comment]
@Abykin could your rebase your branch onto master and resolve the conflict?

**Comment by flukeout** [comment]
Testing this now.

**Comment by flukeout** [comment]
Closing as I've continued this work in #2225 - thanks for your work on this @Abykin - much appreciated!

**Pull request closed without merging**
