### PR TITLE
Fix #1909, #1667: Add GUI display when saving logic is triggered

### LINKED ISSUE #1909: Prompt user when file gets saved to the browser
**What I propose to do**
This is the continuation of an UI update request by @humphd. I will be implementing a new feature that display icon that shows whenever a user is not logged into his thimble account and its document are saved locally to the browser.

**Steps to Reproduce**
User must be logged out
User makes changes and wait for 5 seconds
User jumps through files

**Expected behavior.**
I want the user to be prompt whenever a save occur.

**Actual behavior.**
Nothing is displayed when the document is changed of user moves between files.

**Instrument and Methodologies**
I will be using Firefox and google Chrome browsers to guarantee cross-browser.
I will be using Visual studio Code to ensure that my indentation is compatible with what the development team requires.

### PR DESCRIPTION
**Pull request by humphd**
Builds on work started in https://github.com/mozilla/thimble.mozilla.org/pull/1932 by @Taguiar.  This adds saving indicators for users when they aren't authenticated, and also enhances what we show for authenticated users.

If you are anonymous, it will look like this:

ofline-saving-indicators

If you are logged in, it looks like this (notice that it lets you know about offline and server saving):

auth-saving-indicators

### CODE REVIEW

**Comment by flukeout** [comment]
Cool, some questions @humphd...

* Looks like after making a change in my code, there is about a 5 second timeout before saving those files locally, right?
  * Something about this feels odd to me. I know we can save basically instantly so it's weird to see "Saving..." when I know it's just hanging out and waiting to make a save.
  * It just makes it feel slow and like I want to wait for it to finish or something, needless anticipation.
  * I'll think on some other label or solution, but curious what you think?
* ``All files saved offline`` to me suggests my files are somehow available when I'm "offline" which isn't really the case.
  * We're really talking about all the files being saved locally here, right?
  * I almost think we don't need this label / state indicator at all. It seems like it would be pretty rare that you'll refresh the browser within 5 seconds of a change, and that's all we're really trying to prevent, right?

Will give this a bit more thought and chime in again shortly.

**Comment by humphd** [comment]
Yup, let's perfect this.  First, consider the state of the art:

Google Docs:

dirty-saved

Medium's editor:

medium-example

The `Saving...` I have is really `There are unsaved changes, I'm going to save them soon...`.  That's what Medium's `Unsaved Changes` means; but Google does what I did, `Saving...`.  I'm not sure what's right.  I agree that we should make it feel fast.

`All files saved offline` is going to mean exactly that, once I land the last service worker patch: you can refresh and you'll have them in *this* browser.  Maybe there is better wording?  I'm trying to say:

* offline - saved to indexeddb in this browser, so you can safely close this tab or refresh
* saved to server - synced to Thimble, so you can move to another computer, login, and keep working

Maybe we don't need to indicate both, but I think it helps people understand what is going on?

The reason I moved to always show this was because Google Docs does, so it seemed "normal" to do so.

**Comment by flukeout** [comment]
Yeah, totally understand the points you're making. 

**When signed out**
* Here we only do local saving, and I think the 5 seconds feels slow. Looks like gdocs does every 2 seconds. Can we try that and indicate ``All files saved to browser`` once ``Saving...`` is done?

**When signed in**
* Will it hurt us to do server saving every 2 seconds?
* Additionally, it looks like we fire the event 5 seconds after the first change, even if other changes are made after. Can we defer the save until 2 seconds after the last changes has been made given some reasonable time we wait for between keystrokes?
  * That could reduce our overall save count, because now we're going every 5 seconds no matter what if someone is typing, but we could go just once after 20 seconds of continuous typing.

**Comment by Pomax** [comment]
Is this still a PR we can expect to see landing, or should we close this?

**Comment by Taguiar** [comment]
I thought you have already accepted it. I will continue for sure.

On Jan 18, 2018 1:45 PM, Mike Kamermans <notifications@github.com> wrote:

Is this still a PR we can expect to see landing, or should we close this?

**Comment by Pomax** [comment]
@humphd was this passed by in another PR and can it be closed?

**Comment by humphd** [comment]
Yes, it can be closed.

**Pull request closed without merging**
