### PR TITLE
Fixes #2469 Add scroll in Editor dropdown menu

### LINKED ISSUE #2469: Add scroll in Editor dropdown menu
The last options in the editor dropdown menu hide when the browser window is not maximized and therefore, these options can't be accessed.

editor_dropdown

editor_dropdown2

This is seen in Firefox and Chrome as well.
Maybe, adding a scroll to menu will work...

### PR DESCRIPTION
**Pull request by ayush9398**
Fixes #2469

### CODE REVIEW

**Comment by flukeout** [comment]
Hi @ayush9398 thanks for submitting. Can you please update your PR description to include a reference to the issue you are fixing, in this format...

``Fixes #XXXX`` - where XXXX is the issue number. 

Then, when this PR is merged, that issue will automatically get closed. Thanks!

**Comment by flukeout** [comment]
As far as the PR itself goes, we don't want to set a fixed height on the list of options. Doing this makes it so that we always have to scroll the list if the option we want to change is at the bottom. We only want a scrolling list when there is not enough space to show the whole dialog.

Here are the rules we should apply instead...

```
overflow-y: auto;
max-height: calc(~"100vh - 150px");
```

This makes is so that the scroll bar is shown ONLY when necessary. A value of ``scroll`` shows blank scrollbar even if when scrolling is not possible.

The second rule says, we want a height that is 100% of the height of the available window height - minus 150px. This will ensure that the dialog is always cut off just a bit before the bottom of the editor, like this...

image

Please make the following change in your PR, test it locally in both Chrome and Firefox (or any other browser you are using) and we can get it merged. Thanks!

**Comment by ayush9398** [comment]
@flukeout I have made the changes....

**Comment by flukeout** [comment]
Thanks @ayush9398 - will test right now.

**Comment by flukeout** [comment]
Great, thanks for your work on this @ayush9398 - tested and it works great in both Firefox and Chrome.

**Pull request merged**
