### PR TITLE
Made default pages easier to read and get started with for beginners!

### LINKED ISSUE #2447: Change <title> tag for the default index.html page
Currently both the ``<title>`` and ``<h1>`` have very similar content. I've seen many people start to edit the title expecting to change what they see in the preview because the text matches. It's a small thing but I think we should change it so that the first change people try to make works more reliably.

### PR DESCRIPTION
**Pull request by FinleyCorrigan**
Fixes #2447 

I have updated the default HTML and CSS pages so they are more readable for beginners. I have added comments, and some extra headings, that explain what each one does, in the form of comments. I have done the same thing in the CSS, to less of an extent.

I've probably done a terrible job of explaining what I have done, so please just have a look for yourself!

Hope you guys like my changes, and let's try pass them!

### CODE REVIEW

**Comment by FinleyCorrigan** [comment]
@flukeout

**Comment by flukeout** [comment]
Taking a look now @FinleyCorrigan!

**Comment by flukeout** [comment]
@FinleyCorrigan - My initial impressions of these changes is that they make the editor feel very cluttered and that it requires lots of reading to figure out what is going on (which, I don't think people spend a lot of time doing)..

**Before**

image

**After**

image

However, I like that you've included some extra markup in the index page to get people started. I wonder if a good strategy would be to reduce the number of comments and tags, but include samples for...

* Image
* Link
* List

What are your thoughts?

**Comment by gideonthomas** [comment]
@FinleyCorrigan, thanks for your contribution! Just wanted to also chime in with a note about process for any future contributions: Please do mention your interest in an issue (and wait for it to be assigned to you) before you attempt to fix it so that the project maintainers know who's assigned to what and so that other contributors aren't attempting to fix the same thing you are (which might result in wasted effort). You can find some of our other guidelines in our [CONTRIBUTING.md](https://github.com/mozilla/thimble.mozilla.org/blob/master/CONTRIBUTING.md) file.

**Comment by flukeout** [comment]
Ping @FinleyCorrigan - what do you think of the suggestions I made? Would like to hear your thoughts. Cheers!

**Comment by FinleyCorrigan** [comment]
Hey, sorry for not replying for ages, the emails were going into junk.

I think the suggestions you made sound pretty good, I would be happy for me/someone else to add them.

Kind Regards,
Finley Corrigan
www.finleydoestech.com

**Comment by flukeout** [comment]
Yeah, if you're keen @FinleyCorrigan - please go ahead. You can just push to the same branch with the updated code and the PR will automatically be updated. Let me know!

**Comment by flukeout** [comment]
OK - I'm going to close this so that we can get other people to work on the original issue. We can always re-open later if you'd like to continue. Thanks!

**Pull request closed without merging**
