### PR TITLE
Add Open Graph and Twitter Card Metadata

### PR DESCRIPTION
**Pull request by leereilly**
Hi Mozillians! 👋 

I've noticed that posts on [Twitter]( https://twitter.com/nicashgrove/status/770779387255984128), [Facebook](https://www.facebook.com/shah.zafrani/posts/10210728714231921), and other services that scrape and use websites' [Open Graph](http://ogp.me/) or [Twitter Card](https://dev.twitter.com/cards/overview) metadata don't show any additional information when the [Thimble landing page](https://thimble.mozilla.org) URL is shared. E.g.

screen shot 2016-10-02 at 8 43 35 pm

This PR will help Thimble make a bigger splash on social media, and hopefully result in a noticeable 📈  in referral traffic. Here's what Thimble could look like on Twitter and Facebook respectively when the URL is shared:

screen shot 2016-10-02 at 8 38 15 pm

screen shot 2016-10-02 at 8 38 02 pm

It works for i18n content too. Here's the the additional HTML rendered for US English and Russian landing pages locally in development mode:

### :us: http://localhost:3500/en-US/ (US English)
```html
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@mozlearn">
<meta name="twitter:creator" content="@mozlearn">
<meta name="twitter:title" content="Thimble by Mozilla - An online code editor for learners &amp; educators.">
<meta name="twitter:description" content="Thimble is an online code editor that makes it easy to create and publish your own web pages while learning HTML, CSS &amp;amp; JavaScript.">
<meta name="twitter:image" content="http://localhost:3500/img/social.png">

<meta property="og:url" content="http://localhost:3500/en-US/">
<meta property="og:type" content="website">
<meta property="og:title" content="Thimble by Mozilla - An online code editor for learners &amp; educators.">
<meta property="og:description" content="Thimble is an online code editor that makes it easy to create and publish your own web pages while learning HTML, CSS &amp;amp; JavaScript.">
<meta property="og:image" content="http://localhost:3500/img/social.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
```

### 🇷🇺  http://localhost:3500/ru/ (Russian)

```html
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@mozlearn">
<meta name="twitter:creator" content="@mozlearn">
<meta name="twitter:title" content="Thimble от Mozilla - онлайн редактор кода для изучающих и учителей.">
<meta name="twitter:description" content="Thimble - онлайн редактор кода, который делает простым создание и публикацию ваших веб-страниц, пока вы изучаете HTML, CSS &amp;amp; JavaScript.">
<meta name="twitter:image" content="http://localhost:3500/img/social.png">

<meta property="og:url" content="http://localhost:3500/ru/">
<meta property="og:type" content="website">
<meta property="og:title" content="Thimble от Mozilla - онлайн редактор кода для изучающих и учителей.">
<meta property="og:description" content="Thimble - онлайн редактор кода, который делает простым создание и публикацию ваших веб-страниц, пока вы изучаете HTML, CSS &amp;amp; JavaScript.">
<meta property="og:image" content="http://localhost:3500/img/social.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
```

**Notes:**

* I made the green Thimble image myself (I'm not a very good artist). I'm sure someone else could make something nicer. Something like [this](https://geekdad.com/wp-content/uploads/2015/09/thimble.jpg) maybe?
* I'm not sure if the use of `APP_HOSTNAME ` here is the best approach to getting the server URL? It works locally in dev mode; it should in prod too if that env var is set.

Cheers,
  Lee 🍻 

**PS:** My 8yo son and I have been using Thimble and we both love it! <3

### CODE REVIEW

**Comment by gideonthomas** [comment]
@leereilly thank you very much for contributing! This PR looks great! We're also glad to hear that you and your son enjoy using Thimble!

I think the premise of this PR is great and super helpful in making Thimble more social media friendly. The code itself looks fine to me! cc'ing @flukeout for design input on the image.

Once we have the right image (whether it's the one you've provided or something else), I can merge in this PR.

**Comment by flukeout** [comment]
Thanks for the great work @leereilly! I'll give some thought to the image and update the PR sometime today or tomorrow and we can roll this out.

**Comment by flukeout** [comment]
I dug through some old Social campaign imagery that @sabrinang put together and found some great assets. What do you think?

thimble-share-2

**Comment by flukeout** [comment]
Okay @leereilly , I opened a PR against your social-splash branch with the image above. Once you merge that we can go ahead and get this implemented!

**Comment by leereilly** [comment]
That image is *much* nicer, @flukeout 😻

**Comment by gideonthomas** [comment]
This PR looks good to me! Merging!

Once again, thank you very much for the contribution @leereilly :)

**Comment by leereilly** [comment]
Thanks for the kind words, everyone - t'was my pleasure 🙇 

Thanks for building Thimble *and* open sourcing it :metal:

**Pull request merged**
