### PR TITLE
Fixed indentation

### PR DESCRIPTION
**Pull request by Rajat-dhyani**
Refer to : https://github.com/mozilla/thimble.mozilla.org/pull/1663#issuecomment-276567176

### CODE REVIEW

**Comment by gideonthomas** [comment]
@Rajat-dhyani thank you for the patch!

Would you also be able to remove the `link` tag in `public/resources/default-files/html.txt`

**Comment by Rajat-dhyani** [comment]
@gideonthomas sure sir...

**Comment by Rajat-dhyani** [comment]
@gideonthomas  please refer to https://github.com/mozilla/thimble.mozilla.org/pull/1690 and have it reviewed

**Comment by gideonthomas** [comment]
Looks great! Thank you very much, @Rajat-dhyani!

**Comment by Rajat-dhyani** [comment]
Thanks sir :) @gideonthomas

**Pull request merged**
