### PR TITLE
Fix #1908: Issue 1908 grunt-cli update

### LINKED ISSUE #1908: major-version update several dependencies
based on https://github.com/mozilla/thimble.mozilla.org/pull/1828, let's find all the dependencies that require a major version update, and then tackle them one by one:

- [ ] cryptr
- [ ] fs-writefile-promise
- [ ] glob
- [ ] grunt-cli
- [ ] grunt-contrib-csslint
- [ ] grunt-lesslint
- [ ] jquery
- [ ] helmet
- [ ] wolfy87-eventemitter

### PR DESCRIPTION
**Pull request by badrmodoukh**
I have updated the grunt-cli dependency
I tested using "npm install" and all seems to work fine from my end 
I also ran "vagrant up" and loaded thimble and all worked fine

### CODE REVIEW

**Comment by Pomax** [comment]
Given that there is no changelog information for 0.x I'm willing to merge this in. @humphd objections?

**Comment by humphd** [comment]
No, go for it.  @badrmodoukh my only ask is that when you land these, you go and test https://bramble.mofostaging.net/en-US/ each time once it's deployed so you can see that nothing broke on staging.  If something breaks, we'll just bisect/revert.

**Comment by Pomax** [comment]
@badrmodoukh let me know when you've tested on bramble.mofostaging to make sure the already-landed "these seemed perfectly safe" updates did not lead to problems, and if it looks good, we can merge this one in.

**Comment by badrmodoukh** [comment]
@Pomax @humphd how can I test with bramble.mofostaging. I never tested with it so I am not quite sure how to do it. I usually test using npm install, npm test, and vagrant up which loads thimble in localhost. Can you please let me know

**Comment by humphd** [comment]
@badrmodoukh every time we merge a PR, the code gets built and pushed to our development server, which is https://bramble.mofostaging.net.  You can watch to see when a build gets pushed to staging on Travis: https://travis-ci.org/mozilla/thimble.mozilla.org/branches <-- look at the master branch builds there.  When we finish a build of master, it means that it's available on the staging server.  That means you can go and try running Thimble on staging and see if anything has broken (e.g., try doing some stuff on the staging box and see what happens).

**Comment by flukeout** [comment]
@Pomax how can he test if this works on staging before we merge it in? Is this good to merge now?

**Comment by humphd** [comment]
We can't.  Just merge it, and test on staging, and if it breaks, we can `git revert <commit-sha>` it.

**Comment by flukeout** [comment]
Okay, we've got a bunch of these open PRs, should we just merge them all and take a little bit of time to test together on staging after our call tomorrow?

**Comment by humphd** [comment]
Some can get merged, some need to have fixes applied.  Let's discuss tomorrow.

**Comment by badrmodoukh** [comment]
@Pomax @humphd I tested on bramble.mofostaging and everything seems to work fine on my end

**Comment by humphd** [comment]
@badrmodoukh can you rebase this and fix the conflict, then push it up?

**Pull request merged**
