### PR TITLE
Fixing #2536 : Optimized the Github SVG on the Get Involved page to display properly in Firefox

### PR DESCRIPTION
**Pull request by marcobeltempo**
### Issue
The Github icon on https://thimble.mozilla.org/en-US/get-involved/ was displaying in black when it should have been white.
This only occurred using Firefox.

image

### Fix
As per @flukeout suggestion, I ran [public/resources/img/icon/github-white.svg](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/resources/img/icon/github-white.svg) through https://jakearchibald.github.io/svgomg/ to optimize the SVG

**Tested in**
- Firefox 57
- Chrome 61
- Edge 41

### Result

image

### CODE REVIEW

**Comment by marcobeltempo** [comment]
Thanks for the feedback @gideonthomas! I've applied the recommended changes

**Comment by gideonthomas** [comment]
@marcobeltempo, looks like you might have updated the wrong file. The change should be made to `github-white.svg` instead of `gear-white.svg` in the `public/resources/img/icon` folder.

**Comment by marcobeltempo** [comment]
@gideonthomas I apologize fore the delay and the mix up. I applied the proper changes

**Comment by gideonthomas** [comment]
hmm that is weird! @marcobeltempo can you try rebasing your patch onto what's on master and pushing that up. Hopefully that will fix Appveyor

**Comment by marcobeltempo** [comment]
@gideonthomas I tried rebasing but still no luck

**Comment by gideonthomas** [comment]
hmm, this is so bizzare! @cadecairos any idea what's going on here? The eslint prettier rules that appveyor claims to be violated are firstly, insane, and secondly not caused by this PR.

**Comment by cadecairos** [comment]
This is odd. I've restarted the build... maybe there's a problem with a dependency that had a bad patch update.

**Comment by gideonthomas** [comment]
Wat...now Travis is failing too

**Comment by gideonthomas** [comment]
aha! You're right @cadecairos, looks like a minor version bump in prettier broke stuff. I'll fix this.

**Comment by gideonthomas** [comment]
@marcobeltempo, sorry about that. Looks like one of the dependencies was updated and it broke stuff. I've fixed this on master, so if you rebase again onto master, it should work.

**Comment by marcobeltempo** [comment]
@gideonthomas nice! looks to have done the trick

**Pull request merged**
