### PR TITLE
Fix: 1902 Add a way to hide the preview

### PR DESCRIPTION
**Pull request by Rajat-dhyani**
With this PR we can now toggle the preview window in the same way as the file tree

[Fix:1902](https://github.com/mozilla/thimble.mozilla.org/issues/1902)

### CODE REVIEW

**Comment by flukeout** [comment]
Testing now @Rajat-dhyani

**Comment by flukeout** [comment]
Hey @Rajat-dhyani - getting some strange behaviour with this change...

strange-resizing

Try resizing the some of the views after hiding the preview, and then showing it again. It seems to get messed up pretty quickly.

**Comment by Rajat-dhyani** [comment]
hey @flukeout thanks for review now working on it. @humphd have pointed out some extra stuff that needs to be done with this PR on [bracket's PR](https://github.com/mozilla/brackets/pull/727).
Working on this issue now.

**Comment by Rajat-dhyani** [comment]
@flukeout sir, 
this PR got stalled a bit..could you please check this one out?
brackets' pr: https://github.com/mozilla/brackets/pull/740

cc: @humphd , @gideonthomas , @Pomax

**Comment by flukeout** [comment]
Closing this as we've decided to keep the preview visible always. Thanks for getting this work started @Rajat-dhyani

**Pull request closed without merging**
