### PR TITLE
Fixes #1780

### LINKED ISSUE #1780: Drop down menus on Your Projects page overflow past the edge of the page.
See here...

horiz

### PR DESCRIPTION
**Pull request by hkirat**
Shifted the scope from homepage to global to fix the css overflow on projects page.

### CODE REVIEW

**Comment by Pomax** [comment]
hi @hkirat can you please update your titles so that they describe what the PR is for in the title itself, and then put the "fixes ..." in the comment instead? This lets reviewers go through the open pull request list without having to open every PR to find out what it's actually for (if it's just "fixes #12345" it's impossible to tell what it's for without opening the PR and clicking through to the associated issue)

**Comment by flukeout** [comment]
Hi @hkirat thanks for submitting this. If you take a look at #1780 you'll see that it was already claimed by @rkgupta21. Because of that, we'll go with his PR just to keep things fair. Hope you are okay with that and understand - in the future, please check over the issue history to make sure that nobody is already working on it.

**Comment by hkirat** [comment]
Hey
Thanks for the review.
Modified the title. Will keep the titles more crisp from next time.

**Comment by flukeout** [comment]
Thank you @hkirat!

**Pull request closed without merging**
