### PR TITLE
Fix:2041 Add touch events for the remix bar

### PR DESCRIPTION
**Pull request by Rajat-dhyani**
This adds touch event to remix bar.

 #2041

### CODE REVIEW

**Comment by Rajat-dhyani** [comment]
This PR is stalled 😅
It would be great if some one can review this.
@Pomax @humphd @flukeout @gideonthomas

**Comment by humphd** [comment]
This looks like something @flukeout should review, assigning.

**Comment by flukeout** [comment]
Testing now!

**Comment by flukeout** [comment]
@Rajat-dhyani in testing this I noticed that when I emulate a touch device in Chrome via dev tools, it doesn't think that it is in ``touch-mode``. I tried a different way of detecting touch that I think is better, can you try...

```
var isTouchDevice = (('ontouchstart' in window) || window.DocumentTouch && document instanceof DocumentTouch);
```

Then it starts to work better and you are able to see the "touch mode" version in the dev tools like this...

image

**Comment by Rajat-dhyani** [comment]
sorry for blowing this up 😞 Created new branch and closing this one

**Comment by ryanwarsaw** [comment]
@Rajat-dhyani I've done this a couple of times myself, I really recommend you learn how to undo these types of changes so you don't have to file a new PR every time :)

**Comment by Rajat-dhyani** [comment]
hi @ryanwarsaw can you share some helpful links or resources ? I really wish to know how to undo such mistakes?

**Comment by ryanwarsaw** [comment]
@Rajat-dhyani The way I typically do it is I'll do an interactive rebase on top of whatever branch I'm trying to sync against, and then either commit or force the changes to the feature branch which will leave you with a very clean result and only the changes you've made to that specific branch.

This is a pretty good explanation of how that works: https://git-scm.com/book/en/v2/Git-Branching-Rebasing. If that seems a little too complex, this also is fairly simple and explains how to solve a lot of little interesting situations you may find yourself in: https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history.

**Pull request closed without merging**
