### PR TITLE
Fix #1903: Updated the default/empty project files

### LINKED ISSUE #1903: Update "New Project" style.css to include a nicer font
Honestly, I'm tired of looking at....

image

Since we're already packaging a ``style.css`` file with new projects, we may as well add a few styles to it to make it more attractive and appealing.

As a start, let's add 

```css
body {
  font-family: sans-serif;
}
```

**We could also..**

* Add extra padding around the body
* Change the default background color
  * Would it be possible to generate a dynamic / randomized stylesheet every time a new project is created? That would be cool.
* Include a cool Google Font?

### PR DESCRIPTION
**Pull request by nadia39**
I have added what the specifications were in the description of an issue.

### CODE REVIEW

**Comment by Rajat-dhyani** [comment]
hey @nadia39 you need to mention the issue for which you have file this PR for in your comment so that it links up to the issue like this.
[Fix:1903](https://github.com/mozilla/thimble.mozilla.org/issues/1903)

**Comment by nadia39** [comment]
@Rajat-dhyani Okay, I will do that from now onwards.
Thank you for letting me know

**Comment by humphd** [comment]
Assigning @flukeout for review on this.

**Comment by flukeout** [comment]
Thank you @nadia39 - testing it out now.

**Comment by flukeout** [comment]
Hi @nadia39 - thanks for getting this started. While I appreciate some of the color and style choices you made, I think we have to keep things more basic so that it's still easy to create a new page or document.

I've attached a .zip file that includes an ``index.html`` and ``style.css`` page. Could you please use the content from each of those files in your PR? 

[starter-project-files.zip](https://github.com/mozilla/thimble.mozilla.org/files/938810/starter-project-files.zip)

Thanks and let me know if you have questions!

**Comment by flukeout** [comment]
Hi @nadia39 any updates on this? Let us know - if not we can finish up the work next week. Thanks!

**Comment by flukeout** [comment]
@humphd will finish this work in anticipation of launch.

**Comment by humphd** [comment]
Thanks for getting this started, @nadia39, I've finished the changes @flukeout wanted and landed everything in these commits:

* 9508e01ccd0b9dae6ce447945c00f2925be3d826
* 3ece1cb341c9da6bd0bfb3be4fcb1ac0f2c7f6c8
* 4b241cdbc69ca69e73fbe8700433d632a9c02520

**Pull request closed without merging**
