### PR TITLE
[WIP] Fix:1419 Simplify "getting to a project"

### PR DESCRIPTION
**Pull request by Rajat-dhyani**
Right now you need to click on your username, pick your projects, wait for a new page to load, then click through for there. Instead, now on hovering over "your projects" it automatically has an expansion for picking projects immediately
[FIx:1419](https://github.com/mozilla/thimble.mozilla.org/issues/1419)

### CODE REVIEW

**Comment by Rajat-dhyani** [comment]
As stated {here](https://github.com/mozilla/thimble.mozilla.org/issues/1419#issuecomment-285921439) if we hover over `your project` we can see an extension is added and project list appears if we are on `/projects` page but  i am stuck at how to load project in homepage.

**Comment by flukeout** [comment]
We've got a call later today so I'll make sure one of the team checks in on this, I'm not able to help you myself on this one.

**Comment by Rajat-dhyani** [comment]
@flukeout thanks for letting me know sir.... :)

**Comment by flukeout** [comment]
I'll try this out now - is it ready to test @Rajat-dhyani ?

**Comment by Rajat-dhyani** [comment]
No sir...still cant load projects on homepage @flukeout

**Comment by flukeout** [comment]
Okay - maybe @gideonthomas or @Pomax can help out with some directions.

**Comment by flukeout** [comment]
@Rajat-dhyani - now when you sign in, you are redirected to the projects list, so we have achieved this goal in another way. Seeing as it's quite difficult to get access to the projects list on the homepage, we will be closing this for now. Thanks again for your efforts on this.

**Pull request closed without merging**
