### PR TITLE
Fix #1763:Add UI toggle for whitespace indicators in the editor - continue

### LINKED ISSUE #1763: Add UI toggle for whitespace indicators in the editor.
It would be cool if we could show whitespace within the editor. It makes it easier to indent the code correctly and gets new coders thinking about this important, but easy miss, aspect of coding.

Here's an extension we could try:
https://github.com/DennisKehrig/brackets-show-whitespace

Or maybe there's another way?

For reference, I'm talking about these little dots that appear where a space is...

image

### PR DESCRIPTION
**Pull request by tonypark0403**
[this](https://github.com/mozilla/thimble.mozilla.org/pull/1914) is closed.

### CODE REVIEW

**Comment by tonypark0403** [comment]
@flukeout , it is ready to review and this is connected to [this](https://github.com/mozilla/brackets/pull/702).

**Comment by tonypark0403** [comment]
@flukeout, @humphd I am wondering if there is something wrong because it is still open.

**Comment by flukeout** [comment]
Hey @tonypark0403 - no all good. I'm going to test it one more time and then @humphd will take a look over the code & merge if all is well. Thanks for checking in!

**Comment by flukeout** [comment]
Hi @tonypark0403 - in testing this, it seems that the Editor doesn't persist the setting, so if I turn it ON, and then refresh the browser, it loads again with the setting turned OFF (it should be on).

Can you confirm this is happening on your end too?

**Comment by tonypark0403** [comment]
Hello, @flukeout , @humphd - I fixed it now. Can you check again?
Thank you.

**Comment by tonypark0403** [comment]
@humphd, @flukeout  - I heard it is due tomorrow but no one recheck my result yet. So, here is my result and please accept my result. Thank you.
My result

**Comment by flukeout** [comment]
I'll review this today - sorry for the delay and thanks for checking in!

**Comment by flukeout** [comment]
Hey @tonypark0403 - okay just tested and this works great! The setting is remembered now by the editor, which is what we wanted.

One last change from me.. could you please change the setting label from ``Show WhiteSpace`` to ``Show White Space``? Thank you!

**Comment by flukeout** [comment]
@humphd will land and update the string.

**Comment by humphd** [comment]
Landed in https://github.com/mozilla/thimble.mozilla.org/commit/819bc6ee02565d0795d20aba0ce605ea708f4a8d and https://github.com/mozilla/thimble.mozilla.org/commit/f55b2741a246e78633b8c67c88e95a8b1b1d88ee, closing.

NOTE: I need to land the Brackets piece next (I forgot to land it in the other order).

**Comment by humphd** [comment]
https://github.com/mozilla/brackets/pull/702 is landed now too.

**Pull request closed without merging**
