### PR TITLE
Fixes#2470: Updates Twitter account to @codewiththimble

### LINKED ISSUE #2470: Update Twitter account to @codewiththimble
We are currently linking to [@mozlearn](https://twitter.com/mozlearn) twitter account, but should link to [@codewiththimble](https://twitter.com/codewiththimble) - let's make it happen.

### PR DESCRIPTION
**Pull request by apoorvasingh17**
Fixes #2470

### CODE REVIEW

**Comment by apoorvasingh17** [comment]
@flukeout Please review. Thanks!

**Comment by ryanwarsaw** [comment]
When you're dealing with multiple feature branches, it's important when you create a new feature branch that it's based off of Master, and not whatever branch you're currently on. Otherwise, you get this result (Notice how your commits from another PR are present in this branch as well).

**Comment by apoorvasingh17** [comment]
@ryanwarsaw Should I squash the commits? 
(sorry for the mess, I'm new to git)

**Comment by gideonthomas** [comment]
@apoorvasingh17 try this (assuming your remote name for mozilla/thimble.mozilla.org is called `upstream`):
```
git checkout master
git pull upstream master
git checkout issue/2470/twitter
git rebase --onto master HEAD^
```

if you have conflicts during the rebase step, fix them and then run `git rebase --continue`

Finally force push your changes:
```
git push -f origin issue/2470/twitter
```

**Comment by apoorvasingh17** [comment]
@gideonthomas Thanks! It worked.

**Comment by flukeout** [comment]
Awesome, reviewing today @apoorvasingh17

**Comment by flukeout** [comment]
Much appreciated @apoorvasingh17

**Pull request merged**
