### PR TITLE
Add UI to call bramble.showSelfieDialog()

### PR DESCRIPTION
**Pull request by humphd**
Depends on https://github.com/humphd/brackets/pull/509

### CODE REVIEW

**Comment by gideonthomas** [comment]
r=me

**Comment by humphd** [comment]
I realize I need code to check whether the current browser supports accessing the camera, and hide this if it doesn't.

**Comment by ryanwarsaw** [comment]
@gideonthomas @humphd What's the status on this? Can we close? Link redirects to 404.

**Comment by gideonthomas** [comment]
Done :)

**Pull request closed without merging**
