### PR TITLE
Fix #2196: Rehash inline style for spinner - style src CSP header

### LINKED ISSUE #2196: Update style-src CSP header for inline style
We added the `unsafe-inline` directive for stylesheet CSP here: https://github.com/mozilla/thimble.mozilla.org/blob/master/server/security.js#L54-L56 to allow changes in the loading spinner. Let's revert that by hashing https://github.com/mozilla/thimble.mozilla.org/blob/master/views/editor/bramble.html#L2-L145 again and using that as the CSP rule.

### PR DESCRIPTION
**Pull request by auracle**
@gideonthomas Fixes #2196 
I rehashed the spinner inline style and applied it as the CSP rule. I also removed the previously commented out hash, and the 'unsafe-inline' directive.

### CODE REVIEW

**Comment by gideonthomas** [comment]
Hi @auracle thanks for your contribution. Would you be able to rebase and rehash this? It looks like the code has changed. Sorry about that!

**Comment by auracle** [comment]
Yes Sir! I recalculated the hash to include the new styles. Also, did I do the rebase correctly? Thanks for your time!

**Comment by gideonthomas** [comment]
Hi @auracle, it looks like the rebase didn't happen correctly. There are a bunch of extra commits in here that are already on master.

**Comment by humphd** [comment]
@auracle, assuming your remote for the Mozilla repo is named `upsream` you can do this:

```
git checkout master
git pull upstream master
git checkout -B issue-2196 master
git cherry-pick 7c77df66dd16d3716ed86cbe331ebd6955b4b97c
git push origin issue-2196 -f
```

**Comment by auracle** [comment]
@gideonthomas @cadecairos I recommited the changes to only include the modified file. Please review when you have the chance. Thanks!

@humphd Thank you for the guidance. I really appreciate it!

Thanks for everyones patience as I learn the process!

**Comment by gideonthomas** [comment]
Thanks for the contribution @auracle

**Pull request merged**
