### PR TITLE
Fix#1921: Extended the Gruntfile to include eslint 

### PR DESCRIPTION
**Pull request by badrmodoukh**
@Pomax I installed eslint for grunt and modified the Gruntfile.js file to include the eslint task.
The only rule I can think of to enable and check for is the indent rule. I added it in the .eslintrc.json file and specified that the indent needs to be 2 spaces. If there are any other rules I need to add please let me know.
I also specified the ecmaVersion for the parser to be 6 because if I don't it will give many parsing errors like the keyword `let` is reserved and `const` is reserved.  
Currently when I run `npm test` I get 7 errors because some files don't use 2 spaces. This is how the errors look: 
screen shot 2017-04-09 at 2 59 35 pm

### CODE REVIEW

**Comment by badrmodoukh** [comment]
I fixed the above errors

**Comment by humphd** [comment]
cc @dsych.  Let's build on this PR to also add prettier fix like we are doing in Brackets.  https://github.com/mozilla/brackets/pull/703

**Comment by flukeout** [comment]
Can we merge this @humphd - seems like the problems were addressed.

**Comment by humphd** [comment]
Tested this again today, and it needs a few things:

* This needs to get rebased onto Master, where I found new errors
* The jshint stuff needs to get removed, since eslint does a better job
* We need a set of rules
* We need to fix the errors it produces.

**Comment by gideonthomas** [comment]
Since we're switching to webpack, we would need to run eslint there. Feel free to take on that issue once the webpack code is merged in. Closing, in favor of that.

**Pull request closed without merging**
