### PR TITLE
Fixes #2102 - When switching locales, stay on the same page

### LINKED ISSUE #2102: When switching locales, stay on the same page.
Right now if you navigate to the features page, and then switch the locale, you end up on the homepage. We should keep users on the same page.

### PR DESCRIPTION
**Pull request by Cryzek**
Made changes suggested by @gideonthomas

### CODE REVIEW

**Comment by flukeout** [comment]
Testing this out now.

**Comment by flukeout** [comment]
@Cryzek - is this change working for you? I'm running your PR branch locally and whenever I switch locales on the **Get Involved** or **Features** page, I end up on the homepage. Let me know. Maybe I'm missing some kind of step.

**Comment by Cryzek** [comment]
Yes, it is working properly. 
work1

Could it be a caching problem? Are server-side pages cached?

**Comment by Cryzek** [comment]
Thanks @gideonthomas @flukeout. :blush:

**Comment by flukeout** [comment]
Re-testing now, will report back.

**Comment by flukeout** [comment]
Well, it works as expected! Thanks so much @Cryzek - merging!

**Pull request merged**
