### PR TITLE
Fix#2042: changes XML/SVG option label in the editor dropdown menu

### LINKED ISSUE #2042: Change "XML/SVG" option label in the editor dropdown menu.
This setting lets you edit SVG files...

The label is totally cryptic and doesn't give any indication of what it actually does. Let's change it to something like...

* ``Edit SVG images as Code``
* ``SVG Image Editing``
* ...any other ideas?

### PR DESCRIPTION
**Pull request by apoorvasingh17**
Fixes #2042

### CODE REVIEW

**Comment by apoorvasingh17** [comment]
@flukeout Hi, please review my PR?

**Comment by flukeout** [comment]
Hello @apoorvasingh17 - reviewing now, thank you for submitting.

**Comment by flukeout** [comment]
Hello @apoorvasingh17 - can you please change the label to ``Edit SVG images as code``? It's a bit longer, but I think it makes it easier to understand. Thank you! Also, please add a comment to your Pull Request description like this...

``Fixes #2042``

This will make it so the issue is closed automatically when the PR is merged. Thank you!

**Comment by apoorvasingh17** [comment]
Fixes #2042

**Comment by apoorvasingh17** [comment]
@flukeout Made the changes. Please review. Thanks!

**Comment by flukeout** [comment]
Great, thank you very much!

**Pull request merged**
