### PR TITLE
Video features update

### LINKED ISSUE #2084: Play/Pause videos in Features page on scroll for better performance
The new Cool Features page (see https://bramble.mofostaging.net/en-US/features) is awesome, and does a good job showing how things work, while still keeping download sizes small.  I've tested it on a bunch of machines/browsers/OSes, and especially on Edge, I notice lag in the framerates.  We have a lot of videos (and therefore media threads) running on this page, even when the `video` elements are visible in the viewport.

Let's see if we can add code to call `play()` and `pause()` when the videos scroll into/out-of view, so they don't run all the time.

### PR DESCRIPTION
**Pull request by flukeout**
Based on the awesome start by @Rajat-dhyani this finishes the updates on the features page.

How it works now:
* The first video is set to autoplay
* After that, when you mouse over or touch another video
  * The currently playing video becomes paused
  * That new video starts playing
* There is only ever one video playing at a time now

image

cc @Rajat-dhyani - want to try this out and let me know your thoughts?

Fixes #2084

### CODE REVIEW

**Comment by Rajat-dhyani** [comment]
Greetings Sir @flukeout thanks for tagging me,
This feature looks great now  it definitely reduces the clumsiness of all the inbuilt controls which i had in my branch. I have checked it locally and works fine. But i think there is a little problem
1st you haven't PUSHED your svgs in this branch.
2nd the first video does not stop playing, if i hover over to others first. It only stops if i hover over it first and then onto another.

**Comment by flukeout** [comment]
Good catch on the missing images @Rajat-dhyani - I wonder how I missed that! As for the always playing video, that was kind of the intention, there will always be at least one video playing.

**Comment by flukeout** [comment]
Okay @Rajat-dhyani - please pull my latest changes and you should see the icons. We'll keep the autoplay feature, the goal is to just have one video playing always. Please review when you get a chance thank you! 👍

**Comment by Rajat-dhyani** [comment]
@flukeout okay sir,  checking it now

**Comment by Rajat-dhyani** [comment]
@flukeout, sir i checked it the images have been added. So this is what is happening: 
1- One video has a play button it keeps on playing,it gets paused on hover over it first and then to others but the play image does not change to pause image.
2- Other plays on hover but the pause image does not change to play image 
3- Other then the first video all other have a little darker shade, i think may be because of the background color of `.video-overlay .paused` is set that way.
4- Have you checked touch events its not working for me on firefox like video start playing on touch but other videos does not stop playing, though it works great in chrome. I think you need to add a `changedTouches` event like [this](https://github.com/mozilla/thimble.mozilla.org/pull/2197/commits/405c93beeacc8d2102fb80045be38065ef747905#diff-674339880c3078fd53caf45f1cca6177R16) or something like that.

I can do these changes if you want. Just let me know what you think :)

**Comment by flukeout** [comment]
Hey @Rajat-dhyani - it seems like this whole PR is having some issues on your machine. Here's a GIF of how this is working for me...

_features

Seems like it isn't working in the same way for you? If it's not...

* Are you sure you've got the latest changes I pushed here?
* Did anything have merge conflicts?
* Make sure that you clear your cache and do a hard refresh?

Let me know!

**Comment by flukeout** [comment]
Hello @Rajat-dhyani - are you able to review this patch still? If not, let me know - I can reassign.

**Comment by Rajat-dhyani** [comment]
hey @flukeout sorry for the delay i was afk last weekend. Just got in here...Checking it out now

**Comment by Rajat-dhyani** [comment]
sir @flukeout  i just checked it for chrome, firefox and edge. Its all working great for me (both touch and non-touch) 👍  Kudos :)

**Comment by Pomax** [comment]
This looks pretty good to me!

**Pull request merged**
