### PR TITLE
Don't crash on load when Thimble expects newer Bramble API

### PR DESCRIPTION
**Pull request by humphd**
I have a few bugs in Thimble and Brackets (e.g., #1931) where I'm worrying about startup issues when the Bramble API we have in the Service Worker cache is not the same as what Thimble expects, specifically, when Thimble tries to use some new API call that isn't there in Bramble, and it just crashes and halts startup.  We've improved this a bunch with a couple of fixes to show "reload" buttons; but it still means we might crash, and a user who used to have a working Thimble suddenly doesn't.  That's what I'm most worried about with us launching all this new code.

This PR tries to mitigate that risk by providing default, shimmed versions of new APIs.  We will still want users to update, or some new features won't work fully; but at least we won't crash on startup, and we'll show the new "Reload to get updates" UX.

Eventually I want to get to a place where we don't need this at all; but until then, I think this is a big improvement.  I need to confirm that I've got all the new APIs since we last pushed to prod.  I'll do some more work on this tomorrow morning, when I can confirm what's on prod now.

NOTE: there are other APIs on Bramble for which I'm not providing a fallback implementation.  I'm only focused on the ones that are new, and are used in was that might cause us to crash.

### CODE REVIEW

**Comment by humphd** [comment]
@gideonthomas and/or @cadecairos I need to know the git SHA for what we have on prod for Brackets at the moment, so I can make sure I figure out the diff with `master` and shim all these new APIs.

**Comment by cadecairos** [comment]
bramble-production is running [1c725b89dce7ce3e5f05b256d7f8f6f768fa97f5](https://github.com/mozilla/thimble.mozilla.org/tree/1c725b89dce7ce3e5f05b256d7f8f6f768fa97f5) right now.

**Comment by humphd** [comment]
That's a commit in Thimble, I'm looking for a commit in `mozilla/brackets`.

**Comment by humphd** [comment]
That is, what's https://mozillathimblelivepreview.net/bramble/production/dist/ running?

**Comment by cadecairos** [comment]
aha, apologies. based on the last merge to the production branch that built and [deployed on travis](https://travis-ci.org/mozilla/brackets/builds/175780366) it's [b8dfbc6a20c785437b0441839c3825df72e38dc0](https://github.com/mozilla/brackets/commit/b8dfbc6a20c785437b0441839c3825df72e38dc0)

**Comment by humphd** [comment]
Thanks @cadecairos, this is exactly what I wanted.  Here's the difference in the API, which I'll address with this:

```diff
diff --git a/src/bramble/client/main.js b/src/bramble/client/main.js
index 3a34d1263..f1bfcc1b2 100644
--- a/src/bramble/client/main.js
+++ b/src/bramble/client/main.js
@@ -29,8 +29,8 @@ define([
     "bramble/ChannelUtils",
     "bramble/thirdparty/EventEmitter/EventEmitter.min",
     "bramble/client/StateManager",
-    "bramble/thirdparty/MessageChannel/message_channel"
-], function(Filer, ChannelUtils, EventEmitter, StateManager) {
+    "bramble/client/ProjectStats"
+], function(Filer, ChannelUtils, EventEmitter, StateManager, ProjectStats) {
     "use strict";
 
     // PROD URL for Bramble, which can be changed below
@@ -110,13 +110,15 @@ define([
 
     // Expose Filer for Path, Buffer, providers, etc.
     Bramble.Filer = Filer;
-    var _fs = new Filer.FileSystem();
+    // We wrap the filesystem, and add metrics to keep track of project stats
+    var _fs = ProjectStats.getFileSystem();
     Bramble.getFileSystem = function() {
         return _fs;
     };
+    
     // NOTE: THIS WILL DESTROY DATA! For error cases only, or to wipe the disk.
     Bramble.formatFileSystem = function(callback) {
-        _fs = new Filer.FileSystem({flags: ["FORMAT"]}, callback);
+        _fs = ProjectStats.formatFileSystem({flags: ["FORMAT"]}, callback);
     };
 
     // Start loading Bramble's resources, setup communication with iframe
@@ -147,7 +149,14 @@ define([
             return;
         }
 
-        _instance.mount(root, filename);
+        ProjectStats.init(root, function(err){
+            if(err) {
+                setReadyState(Bramble.ERROR, new Error("Unable to access filesystem: ", err));
+                return;
+            }
+            _instance.mount(root, filename);
+        });
+
     };
 
     /**
@@ -204,8 +213,17 @@ define([
         self.getSidebarVisible = function() { return _state.sidebarVisible; };
         self.getRootDir = function() { return _root; };
         self.getWordWrap = function() { return _state.wordWrap; };
+        self.getAutocomplete = function() { return _state.allowAutocomplete; };
+        self.getAutoCloseTags = function() { return _state.autoCloseTags; };
+        self.getAllowJavaScript = function() { return _state.allowJavaScript; };
+        self.getAllowWhiteSpace = function() { return _state.allowWhiteSpace; };
+        self.getAutoUpdate = function() { return _state.autoUpdate; };
+        self.getOpenSVGasXML = function() { return _state.openSVGasXML; };
         self.getTutorialExists = function() { return _tutorialExists; };
         self.getTutorialVisible = function() { return _tutorialVisible; };
+        self.getTotalProjectSize = function() { return ProjectStats.getTotalProjectSize(); };
+        self.hasIndexFile =  function() { return ProjectStats.hasIndexFile(); };
+        self.getFileCount = function() { return ProjectStats.getFileCount(); };
         self.getLayout = function() {
             return {
                 sidebarWidth: _state.sidebarWidth,
@@ -228,7 +246,18 @@ define([
             addEventListener("message", function(e) {
                 var data = parseEventData(e.data);
 
-                // When Bramble is ready for the filesystem to be mounted, it will let us know
+                // Deal with messages from the service worker regarding cache. We trigger these
+                // events on Bramble vs. the bramble instance.
+                if(data.type === "Bramble:updatesAvailable") {
+                    Bramble.trigger("updatesAvailable");
+                    return;
+                }
+                if(data.type === "Bramble:offlineReady") {
+                    Bramble.trigger("offlineReady");
+                    return;
+                }
+
+                // When bramble instance is ready for the filesystem to be mounted, it will let us know
                 if (data.type === "bramble:readyToMount") {
                     debug("bramble:readyToMount");
                     setReadyState(Bramble.MOUNTABLE);
@@ -262,6 +291,12 @@ define([
                     _state.previewMode = data.previewMode;
                     _state.theme = data.theme;
                     _state.wordWrap = data.wordWrap;
+                    _state.autoCloseTags = data.autoCloseTags;
+                    _state.allowJavaScript = data.allowJavaScript;
+                    _state.allowWhiteSpace = data.allowWhiteSpace;
+                    _state.autocomplete = data.autocomplete;
+                    _state.autoUpdate = data.autoUpdate;
+                    _state.openSVGasXML = data.openSVGasXML;
 
                     setReadyState(Bramble.READY);
                 }
@@ -297,8 +332,20 @@ define([
                         _state.sidebarVisible = data.visible;
                     } else if (eventName === "wordWrapChange") {
                         _state.wordWrap = data.wordWrap;
+                    } else if (eventName === "autoCloseTagsChange") {
+                        _state.autoCloseTags = data.autoCloseTags;
+                    } else if (eventName === "openSVGasXMLChange") {
+                        _state.openSVGasXML = data.openSVGasXML;
+                    } else if (eventName === "allowJavaScriptChange") {
+                        _state.allowJavaScript = data.allowJavaScript;
+                    } else if (eventName === "allowWhiteSpaceChange") {
+                        _state.allowWhiteSpace = data.allowWhiteSpace;
                     } else if (eventName === "tutorialVisibilityChange") {
                         _tutorialVisible = data.visible;
+                    } else if (eventName === "autocompleteChange") {
+                        _state.allowAutocomplete = data.value;
+                    } else if (eventName === "autoUpdateChange") {
+                        _state.autoUpdate = data.autoUpdate;
                     }
 
                     debug("triggering remote event", eventName, data);
@@ -412,7 +459,13 @@ define([
                                     firstPaneWidth: _state.firstPaneWidth,
                                     secondPaneWidth: _state.secondPaneWidth,
                                     previewMode: _state.previewMode,
-                                    wordWrap: _state.wordWrap
+                                    wordWrap: _state.wordWrap,
+                                    allowAutocomplete: _state.allowAutocomplete,
+                                    autoCloseTags: _state.autoCloseTags,
+                                    autoUpdate: _state.autoUpdate,
+                                    openSVGasXML: _state.openSVGasXML,
+                                    allowJavaScript: _state.allowJavaScript,
+                                    allowWhiteSpace: _state.allowWhiteSpace
                                 }
                             };
                             _brambleWindow.postMessage(JSON.stringify(initMessage), _iframe.src);
@@ -436,10 +489,11 @@ define([
 
         function setupChannel(win) {
             var channel = new MessageChannel();
-            ChannelUtils.postMessage(win,
-                                     [JSON.stringify({type: "bramble:filer"}),
-                                     "*",
-                                     [channel.port2]]);
+            win.postMessage(
+                JSON.stringify({type: "bramble:filer"}),
+                "*",
+                [channel.port2]
+            );
             _port = channel.port1;
             _port.start();
 
@@ -735,7 +789,14 @@ define([
                         // If the path was a file, immediately unlink
                         // trigger the event, and call the callback
                         if(err.code === "ENOTDIR") {
-                            return shell.rm(path, genericFileEventFn("fileDelete", path, callback));
+                            return shell.rm(path, genericFileEventFn("fileDelete", path, function(err) {
+                            	var wrappedCallback = callback;
+                            	if(!err && path === self.tutorialPath) {
+                            	   wrappedCallback = genericFileEventFn("tutorialRemoved", path, wrappedCallback);
+                            	   _tutorialExists = false;
+                            	}
+                            	wrappedCallback(err);
+                            }));
                         }
 
                         return callback(err);
@@ -894,6 +955,30 @@ define([
         this._executeRemoteCommand({commandCategory: "bramble", command: "BRAMBLE_DISABLE_SCRIPTS"}, callback);
     };
 
+    BrambleProxy.prototype.enableWhiteSpace = function(callback) {
+        this._executeRemoteCommand({commandCategory: "bramble", command: "BRAMBLE_ENABLE_WHITESPACE"}, callback);
+    };
+
+    BrambleProxy.prototype.disableWhiteSpace = function(callback) {
+        this._executeRemoteCommand({commandCategory: "bramble", command: "BRAMBLE_DISABLE_WHITESPACE"}, callback);
+    };
+
+    BrambleProxy.prototype.enableAutocomplete = function(callback) {
+        this._executeRemoteCommand({commandCategory: "bramble", command: "BRAMBLE_ENABLE_AUTOCOMPLETE"}, callback);
+    };
+
+    BrambleProxy.prototype.disableAutocomplete = function(callback) {
+        this._executeRemoteCommand({commandCategory: "bramble", command: "BRAMBLE_DISABLE_AUTOCOMPLETE"}, callback);
+    };
+
+    BrambleProxy.prototype.openSVGasXML = function(callback) {
+        this._executeRemoteCommand({commandCategory: "bramble", command: "BRAMBLE_OPEN_SVG_AS_XML"}, callback);
+    };
+
+    BrambleProxy.prototype.openSVGasImage = function(callback) {
+        this._executeRemoteCommand({commandCategory: "bramble", command: "BRAMBLE_OPEN_SVG_AS_IMAGE"}, callback);
+    };
+
     BrambleProxy.prototype.enableInspector = function(callback) {
         this._executeRemoteCommand({commandCategory: "bramble", command: "BRAMBLE_ENABLE_INSPECTOR"}, callback);
     };
@@ -910,6 +995,10 @@ define([
         this._executeRemoteCommand({commandCategory: "bramble", command: "BRAMBLE_DISABLE_WORD_WRAP"}, callback);
     };
 
+    BrambleProxy.prototype.configureAutoCloseTags = function(options, callback) {
+        this._executeRemoteCommand({commandCategory: "bramble", command: "BRAMBLE_CONFIGURE_AUTO_CLOSE_TAGS", args: [ options ]}, callback);
+    };
+
     BrambleProxy.prototype.showTutorial = function(callback) {
         this._executeRemoteCommand({commandCategory: "bramble", command: "BRAMBLE_SHOW_TUTORIAL"}, callback);
     };
@@ -944,5 +1033,13 @@ define([
         this._executeRemoteCommand({commandCategory: "bramble", command: "BRAMBLE_EXPORT"}, callback);
     };
 
+    BrambleProxy.prototype.addCodeSnippet = function(options, callback) {
+        this._executeRemoteCommand({
+            commandCategory: "bramble",
+            command: "BRAMBLE_ADD_CODE_SNIPPET",
+            args: [options]
+        }, callback);
+    };
+
     return Bramble;
 });
```

**Comment by humphd** [comment]
I've updated to match that Brackets commit, and now shim all the new APIs if they are missing.  To show you why this is important, I tried running the new Thimble code with the old Brackets commit (what's on prod now).  If a user has loaded Thimble previously, and tries to run our new release, this is what they will get:

screen shot 2017-05-15 at 11 08 54 am

With my API shim, this is what they will get:

screen shot 2017-05-15 at 11 30 07 am

@gideonthomas can you review this please?  Have I missed anything?

**Comment by humphd** [comment]
Filed https://github.com/mozilla/thimble.mozilla.org/issues/2101 to remove this later.

**Pull request merged**
