### PR TITLE
Fixing line Height is too small - Issue #1988

### LINKED ISSUE #1988: Line height is too small
screen shot 2017-04-12 at 2 03 53 pm

In the publish dialog, the bottom of the `g` in the url is cut off because the line height is set to the same value as the font-size we're using. I think we probably just need to either remove the line-height or set it to something bigger. If we want to maintain the same space in the blue box, we can reduce the padding.

cc @flukeout

### PR DESCRIPTION
**Pull request by morrme**
Modified padding and removed line-height for the publish-link.

Fixes #1988

### CODE REVIEW

**Comment by morrme** [comment]
@gideonthomas @flukeout For your review 🤓

**Comment by flukeout** [comment]
Testing it out now @morrme

**Comment by flukeout** [comment]
Hey @morrme thanks for this. The blue box still has a wider space below the link...

image

Let's fix this up. We can change the ``#link_publish_link`` (lol @ that ID) to have ``display: block'' instead of ``display:inline-block``. If you could update your PR with that change, then we'll be set, thank you!

**Comment by morrme** [comment]
@flukeout OK, making the change now. Should I remove the `padding` property as well?

**Comment by flukeout** [comment]
@morrme do you mean on the parent element of the link? No let's leave that. The link element itself doesn't have any padding, right?

**Comment by morrme** [comment]
@flukeout thanks! done.

**Comment by flukeout** [comment]
Ahhhh @morrme - I'm an idiot. I remember now why ``display: inline-block`` is better.

* For one, try to highlight to copy paste the link now, it's harder because the link spans the whole blue box and you start dragging it.
* Second, when you hover anywhere over the blue box, the link gets an underline and you can click it, which is weird.

Sorry about that!

So what we should do it...

* make it ``inline-block`` again
* change the padding of the parent element to ``padding: 10px 12px 5px 12px;`` so that the blue box has even padding around the link. Should look like this still...
* Also, then lets slap a ``max-width: 100%;`` on the link element, so that if the URL is longer than the allowed space, it will properly add the ``...`` at the end and cut it off.



Thanks!!

**Comment by morrme** [comment]
@flukeout Not at all! In making that attempt, I learned something new about the nuances between the two attributes.  :smiley:

**Comment by flukeout** [comment]
Awesome, thank you @morrme - merging!

**Pull request merged**
